Create parser
darkace2707/admiralbd pull request #7
Opened 2021-04-11 23:10 UTC by darkace2707

excel parser for Deaprtures

2021-04-11 23:22 UTC, Kot1que requested changes

2021-04-11 23:22 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/AdmiralbdApplication.java
> +//        List<Departure> departureList = ExcelParser.readFromExcel(file);
Мусор

2021-04-11 23:22 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/models/Departure.java
> +        return "Departure{" +
`@ToString` ломбока есть

2021-04-11 23:22 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +                if (!departureEmpty) {
Инвертируй иф

2021-04-12 08:44 UTC, Kot1que requested changes

2021-04-12 08:44 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +    public static List<Departure> readFromExcel(File file) throws IOException {
я бы сделал метод не статичным, в конструктор можно добавить `File`, но не открывать его чтоб было лениво (т.е. использование может быть сильно позднее инициализации класса, поэтому файл нет смысла сразу открывать).

2021-04-12 08:44 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +
Можно так)
```java
sheet.stream().skip(1).forEach(row -> {
...
})
```

2021-04-12 12:41 UTC, darkace2707 commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +
я так и хотел но у shee нет стрима

2021-04-12 13:30 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +
`StreamSupport.stream(sheet.spliterator())`

2021-04-12 14:35 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +                if (departureEmpty) return;
лучше проверку в метод вынести, иначе выглядит как магия

2021-04-12 14:44 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +
еще обернуть в try-with-resources

2021-04-12 17:16 UTC, Kot1que requested changes

2021-04-12 17:16 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/AdmiralbdApplication.java
> +        System.out.println(l.get(0));
))

2021-04-12 17:16 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +    }
давай все-таки в отдельный класс. Этот класс парсер, а эта часть хорошо ложится на "маппер".

2021-04-12 17:16 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/parser/ExcelParser.java
> +                    Fields fields = new Fields();
инициализируй маппер за циклами

2021-04-12 19:52 UTC, Kot1que approved these changes

2021-04-12 20:07 UTC, merged