Create tree table
darkace2707/admiralbd pull request #9
Opened 2021-04-15 13:18 UTC by darkace2707

tree tables in consignorView

2021-04-15 14:56 UTC, Kot1que requested changes

2021-04-15 14:56 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/models/Node.java
> +    private String pid; // parent id
первый коммент бесполезный, второй коммент можно убрать если не экономить байты в названии переменной - `parentId`

2021-04-15 14:56 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/models/Node.java
> +    }
`@ToString`

2021-04-15 14:56 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/models/Node.java
> +    private String pid; // parent id
еще посмотри в сторону `@Data` ломбока

2021-04-15 14:56 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/services/DepartureServiceImpl.java
> +        }
тут с отступами вообще беда

2021-04-15 14:56 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/services/DepartureServiceImpl.java
> +        departureStationRFCountTree.forEach(d -> overall.addAndGet(d.getCount()));
`Integer count = departureStationRFCountTree.stream().map(<какой-то класс, который у тебя помечен d>::getCount()).reduce(0, Integer::sum)`
вроде так

2021-04-15 14:56 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/services/DepartureServiceImpl.java
> +                                d.getDestinationWay().equals(destinationWay))
```java
.filter(departureStationRF::equals)
.filter(destinationWay::equals)
```
попробуй так, по-моему прикольнее выглядит

2021-04-15 14:56 UTC, Kot1que commented on src/main/java/ru/admiralnsk/admiralbd/services/DepartureServiceImpl.java
> +    }
вообще подумай над рефакторингом метода. У него, кажется. несколько логических блоков, которые можно хотя бы по нескольким методам разбросать

2021-04-15 19:20 UTC, darkace2707 commented on src/main/java/ru/admiralnsk/admiralbd/services/DepartureServiceImpl.java
> +                                d.getDestinationWay().equals(destinationWay))
там же сначала достается геттерем и только потом иквалс на стрингах, так не получится

2021-04-16 21:10 UTC, Kot1que approved these changes

2021-04-18 14:20 UTC, merged